ALTER TABLE business_profiles
    ADD COLUMN ein_status ENUM('unknown','not_requested','requested','issued') NOT NULL DEFAULT 'unknown' AFTER formation_date,
    ADD COLUMN industry VARCHAR(160) NULL AFTER ein_status,
    ADD COLUMN business_description TEXT NULL AFTER industry,
    ADD COLUMN domain_name VARCHAR(255) NULL AFTER website,
    ADD COLUMN domain_registrar VARCHAR(160) NULL AFTER domain_name,
    ADD COLUMN email_provider VARCHAR(160) NULL AFTER domain_registrar,
    ADD COLUMN social_profiles JSON NULL AFTER email_provider;

CREATE TABLE client_addresses (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
    client_id BIGINT UNSIGNED NOT NULL,
    address_type ENUM('principal','business','mailing','other') NOT NULL,
    label VARCHAR(100) NULL,
    line1 VARCHAR(180) NOT NULL,
    line2 VARCHAR(180) NULL,
    city VARCHAR(120) NOT NULL,
    state VARCHAR(120) NOT NULL,
    postal_code VARCHAR(50) NOT NULL,
    country VARCHAR(120) NOT NULL DEFAULT 'United States',
    is_current TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id), UNIQUE KEY uq_client_addresses_public_id (public_id),
    KEY idx_client_addresses_client_type (client_id, address_type, is_current),
    CONSTRAINT fk_client_addresses_client FOREIGN KEY (client_id) REFERENCES clients (id) ON UPDATE RESTRICT ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE client_business_people (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
    client_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(180) NOT NULL,
    role_type ENUM('owner','member','authorized_contact','decision_maker','other') NOT NULL,
    title VARCHAR(120) NULL,
    email VARCHAR(254) NULL,
    phone VARCHAR(40) NULL,
    ownership_percentage DECIMAL(5,2) NULL,
    is_primary TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    archived_at TIMESTAMP(6) NULL DEFAULT NULL,
    PRIMARY KEY (id), UNIQUE KEY uq_client_business_people_public_id (public_id),
    KEY idx_client_business_people_client_role (client_id, role_type, archived_at),
    CONSTRAINT fk_client_business_people_client FOREIGN KEY (client_id) REFERENCES clients (id) ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT chk_client_business_people_ownership CHECK (ownership_percentage IS NULL OR (ownership_percentage >= 0 AND ownership_percentage <= 100))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE intake_assignments (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
    client_id BIGINT UNSIGNED NOT NULL,
    engagement_id BIGINT UNSIGNED NOT NULL,
    family_key ENUM('client_profile','business_formation','business_consulting','web_digital','notary','document_admin','ongoing_support') NOT NULL,
    module_keys JSON NOT NULL,
    status ENUM('assigned','in_progress','submitted','under_review','changes_requested','approved','archived') NOT NULL DEFAULT 'assigned',
    completion_percentage TINYINT UNSIGNED NOT NULL DEFAULT 0,
    assigned_by_user_id BIGINT UNSIGNED NOT NULL,
    assigned_to_user_id BIGINT UNSIGNED NULL,
    due_date DATE NULL,
    submitted_at TIMESTAMP(6) NULL DEFAULT NULL,
    reviewed_at TIMESTAMP(6) NULL DEFAULT NULL,
    reviewed_by_user_id BIGINT UNSIGNED NULL,
    client_visible_review_note TEXT NULL,
    internal_review_notes TEXT NULL,
    blocking_reason VARCHAR(500) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    archived_at TIMESTAMP(6) NULL DEFAULT NULL,
    PRIMARY KEY (id), UNIQUE KEY uq_intake_assignments_public_id (public_id),
    UNIQUE KEY uq_intake_assignments_engagement_family (engagement_id, family_key),
    KEY idx_intake_assignments_client_status (client_id, status, due_date),
    CONSTRAINT fk_intake_assignments_client FOREIGN KEY (client_id) REFERENCES clients (id) ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_intake_assignments_engagement FOREIGN KEY (engagement_id) REFERENCES engagements (id) ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_intake_assignments_assigner FOREIGN KEY (assigned_by_user_id) REFERENCES users (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_intake_assignments_assignee FOREIGN KEY (assigned_to_user_id) REFERENCES users (id) ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT fk_intake_assignments_reviewer FOREIGN KEY (reviewed_by_user_id) REFERENCES users (id) ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT chk_intake_assignments_completion CHECK (completion_percentage <= 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE intake_responses (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
    intake_assignment_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NOT NULL,
    section_key VARCHAR(100) NOT NULL,
    field_key VARCHAR(120) NOT NULL,
    response_value JSON NULL,
    applicability ENUM('required','optional','not_applicable','already_on_file') NOT NULL DEFAULT 'optional',
    answered_by_user_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id), UNIQUE KEY uq_intake_responses_public_id (public_id),
    UNIQUE KEY uq_intake_responses_assignment_field (intake_assignment_id, section_key, field_key),
    KEY idx_intake_responses_client_assignment (client_id, intake_assignment_id),
    CONSTRAINT fk_intake_responses_assignment FOREIGN KEY (intake_assignment_id) REFERENCES intake_assignments (id) ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_intake_responses_client FOREIGN KEY (client_id) REFERENCES clients (id) ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_intake_responses_answerer FOREIGN KEY (answered_by_user_id) REFERENCES users (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE intake_requirements (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
    intake_assignment_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NOT NULL,
    engagement_id BIGINT UNSIGNED NOT NULL,
    requirement_key VARCHAR(120) NOT NULL,
    requirement_name VARCHAR(180) NOT NULL,
    requirement_type ENUM('document','asset','information','access') NOT NULL,
    necessity ENUM('required','optional','not_applicable') NOT NULL DEFAULT 'required',
    status ENUM('missing','already_on_file','provided','under_review','accepted','replacement_requested','not_applicable') NOT NULL DEFAULT 'missing',
    document_id BIGINT UNSIGNED NULL,
    notes VARCHAR(500) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id), UNIQUE KEY uq_intake_requirements_public_id (public_id),
    UNIQUE KEY uq_intake_requirements_assignment_key (intake_assignment_id, requirement_key),
    KEY idx_intake_requirements_client_status (client_id, status),
    CONSTRAINT fk_intake_requirements_assignment FOREIGN KEY (intake_assignment_id) REFERENCES intake_assignments (id) ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_intake_requirements_client FOREIGN KEY (client_id) REFERENCES clients (id) ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_intake_requirements_engagement FOREIGN KEY (engagement_id) REFERENCES engagements (id) ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_intake_requirements_document FOREIGN KEY (document_id) REFERENCES documents_metadata (id) ON UPDATE RESTRICT ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
