<?php

declare(strict_types=1);

final class AlchemizeIntakeService
{
    public function __construct(private readonly AlchemizeIntakeRepository $repository, private readonly AlchemizeActivityRepository $activities) {}

    public function list(array $access): array { return ['items'=>$this->repository->listForClient((int)$access['client_id']),'profile'=>$this->repository->profile((int)$access['client_id'])]; }

    public function get(array $access,string $id): array
    {
        $assignment=$this->repository->findForClient($id,(int)$access['client_id']); if($assignment===null)$this->notFound();
        $definitions=alchemize_intake_definitions(); $definition=$definitions[$assignment['family_key']]??null; if($definition===null)$this->notFound();
        $definition['modules']=array_values(array_filter($definition['modules'],fn($m)=>in_array($m['key'],$assignment['module_keys'],true)));
        $assignment['completion_percentage']=$this->completion($assignment,(int)$access['client_id']);
        $requirements=$this->repository->requirements((int)$assignment['id']);foreach($requirements as &$requirement)$requirement['eligible_documents']=$this->repository->eligibleDocuments((int)$access['client_id'],(string)$requirement['requirement_key']);unset($requirement);
        return ['assignment'=>$assignment,'definition'=>$definition,'responses'=>$this->repository->responses((int)$assignment['id'],(int)$access['client_id']),'requirements'=>$requirements,'profile'=>$this->repository->profile((int)$access['client_id'])];
    }

    public function save(array $access,array $user,string $id,array $payload): array
    {
        $assignment=$this->repository->findForClient($id,(int)$access['client_id'],true); if($assignment===null)$this->notFound();
        if(in_array($assignment['status'],['submitted','under_review','approved','archived'],true))throw new AlchemizeRequestException(409,'INTAKE_LOCKED','This intake is currently locked for review.');
        $allowed=$this->fieldMap($assignment); $responses=is_array($payload['responses']??null)?$payload['responses']:[]; $profile=$this->repository->profile((int)$access['client_id']); $existing=$this->repository->responses((int)$assignment['id'],(int)$access['client_id']);
        foreach($responses as $key=>$item){ if(!isset($allowed[$key]))throw new AlchemizeRequestException(422,'VALIDATION_ERROR','The intake contains an unsupported field.'); $value=is_array($item)&&array_key_exists('value',$item)?$item['value']:$item; $defaultApp=$allowed[$key]['required']?'required':'optional'; $submittedApp=is_array($item)?(string)($item['applicability']??$defaultApp):$defaultApp; $existingApp=(string)($existing[$key]['applicability']??''); $app=in_array($existingApp,['not_applicable','already_on_file'],true)&&$submittedApp===$existingApp?$existingApp:$defaultApp; if($app==='already_on_file'&&!$this->profileHasValue($profile,$key))throw new AlchemizeRequestException(422,'ALREADY_ON_FILE_UNAVAILABLE','This information is not currently available in the Client Profile.'); if(in_array($allowed[$key]['type'],['address_refs','person_refs'],true)){$value=$this->validateReferences($assignment,(int)$access['client_id'],$key,$allowed[$key]['type'],(array)$value);} $encoded=json_encode($value,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR); if(strlen($encoded)>20000)throw new AlchemizeRequestException(422,'VALIDATION_ERROR','An intake response is too long.'); $this->repository->saveResponse(['public_id'=>alchemize_uuid_v4(),'intake_assignment_id'=>$assignment['id'],'client_id'=>$access['client_id'],'section_key'=>$allowed[$key]['section'],'field_key'=>$key,'response_value'=>$encoded,'applicability'=>$app,'answered_by_user_id'=>$user['user_id']]); }
        if($assignment['family_key']==='client_profile'){$canonical=[];foreach($responses as $key=>$item){$canonical[$key]=is_array($item)&&array_key_exists('value',$item)?$item['value']:$item;}$this->repository->updateCanonicalProfile((int)$access['client_id'],$canonical);}
        $completion=$this->completion($assignment,(int)$access['client_id']); $this->repository->updateAssignment((int)$assignment['id'],['status'=>'in_progress','completion_percentage'=>$completion]); return ['id'=>$id,'completion_percentage'=>$completion,'saved'=>count($responses)];
    }

    public function saveAddress(array $access,?string $id,array $payload):array{$v=$this->addressValues($payload);$public=$id===null?$this->repository->createAddress((int)$access['client_id'],$v):$id;if($id!==null&&!$this->repository->updateAddress($id,(int)$access['client_id'],$v))$this->notFound();return ['id'=>$public];}
    public function removeAddress(array $access,string $id):array{if(!$this->repository->removeAddress($id,(int)$access['client_id']))$this->notFound();return ['id'=>$id,'removed'=>true];}
    public function savePerson(array $access,?string $id,array $payload):array{$v=$this->personValues($payload);$public=$id===null?$this->repository->createPerson((int)$access['client_id'],$v):$id;if($id!==null&&!$this->repository->updatePerson($id,(int)$access['client_id'],$v))$this->notFound();return ['id'=>$public];}
    public function removePerson(array $access,string $id):array{if(!$this->repository->removePerson($id,(int)$access['client_id']))$this->notFound();return ['id'=>$id,'removed'=>true];}
    public function prepareRequirementUpload(array $access,array $user,string $assignmentId,string $requirementId):array{$r=$this->repository->findRequirement($requirementId,$assignmentId,(int)$access['client_id'],true);if($r===null)$this->notFound();if(!in_array($r['requirement_type'],['document','asset'],true))throw new AlchemizeRequestException(422,'VALIDATION_ERROR','This requirement does not accept a file.');$document=$r['document_id']?['id'=>(int)$r['document_id'],'public_id'=>(string)$this->repository->authorizedDocumentByInternalId((int)$r['document_id'],(int)$access['client_id'])['public_id']]:$this->repository->createRequirementDocument($r);$this->repository->updateRequirement((int)$r['id'],['document_id'=>$document['id'],'status'=>'missing']);$this->repository->addRequirementHistory((int)$r['id'],$document['id'],'upload_requested',null,(int)$user['user_id']);return ['document_id'=>$document['public_id'],'requirement_id'=>$requirementId,'return_to'=>'/client-portal/intake?assignment='.rawurlencode($assignmentId)];}
    public function useExisting(array $access,array $user,string $assignmentId,string $requirementId,string $documentId):array{$r=$this->repository->findRequirement($requirementId,$assignmentId,(int)$access['client_id'],true);if($r===null)$this->notFound();$d=$this->repository->authorizedDocument($documentId,(int)$access['client_id'],true);if($d===null||($d['document_type']??'')!==$r['requirement_key'])$this->notFound();$this->repository->updateRequirement((int)$r['id'],['document_id'=>$d['id'],'status'=>'already_on_file','notes'=>null]);$this->repository->addRequirementHistory((int)$r['id'],(int)$d['id'],'already_on_file',null,(int)$user['user_id']);return ['requirement_id'=>$requirementId,'status'=>'already_on_file'];}

    public function submit(array $access,array $user,string $id): array
    {
        $assignment=$this->repository->findForClient($id,(int)$access['client_id'],true); if($assignment===null)$this->notFound(); $completion=$this->completion($assignment,(int)$access['client_id']);
        if($completion<100)throw new AlchemizeRequestException(422,'INTAKE_INCOMPLETE','Complete all required intake questions before submitting.');
        $this->repository->updateAssignment((int)$assignment['id'],['status'=>'submitted','completion_percentage'=>100,'submitted_at'=>date('Y-m-d H:i:s.u')]);
        $this->activities->create(['public_id'=>alchemize_uuid_v4(),'event_type'=>'client.intake.submitted','actor_type'=>'client','actor_user_id'=>$user['user_id'],'entity_type'=>'intake','entity_id'=>$id,'client_id'=>$access['client_id'],'engagement_id'=>$assignment['engagement_id'],'summary'=>'Client submitted an engagement intake for review.','visibility'=>'both']); return ['id'=>$id,'status'=>'submitted'];
    }

    private function fieldMap(array $assignment):array{$definition=alchemize_intake_definitions()[$assignment['family_key']]??[];$map=[];foreach(($definition['modules']??[]) as $module){if(!in_array($module['key'],$assignment['module_keys'],true))continue;foreach($module['fields'] as $field)$map[$field['key']]=['section'=>$module['key'],'required'=>(bool)$field['required'],'type'=>$field['type'],'show_when'=>$field['show_when']??null];}return $map;}
    private function completion(array $assignment,int $clientId):int{$map=$this->fieldMap($assignment);$responses=$this->repository->responses((int)$assignment['id'],$clientId);$required=array_filter($map,fn($f)=>$f['required']);$done=0;$values=array_map(fn($r)=>$r['value'],$responses);foreach($required as $key=>$field){$condition=$field['show_when'];if($condition&&(($values[$condition['field']]??null)!==$condition['equals']))continue;$response=$responses[$key]??null;if($response&&in_array($response['applicability'],['not_applicable','already_on_file'],true)){$done++;continue;}$value=$response['value']??null;if($value!==null&&$value!==''&&$value!==[])$done++;}$requiredDocs=array_filter($this->repository->requirements((int)$assignment['id']),fn($r)=>$r['necessity']==='required');$total=count(array_filter($required,function($field)use($values){$c=$field['show_when'];return !$c||(($values[$c['field']]??null)===$c['equals']);}))+count($requiredDocs);foreach($requiredDocs as $r)if(in_array($r['status'],['under_review','accepted','already_on_file','not_applicable'],true))$done++;return $total===0?100:(int)floor($done*100/$total);}
    private function validateReferences(array $assignment,int $clientId,string $field,string $type,array $ids):array{$records=[];foreach(array_values(array_unique($ids)) as $id){$record=$type==='address_refs'?$this->repository->address((string)$id,$clientId):$this->repository->person((string)$id,$clientId);if($record===null)throw new AlchemizeRequestException(422,'PROFILE_REFERENCE_INVALID','One or more selected profile records are unavailable.');$records[]=$record;}$this->repository->replaceProfileReferences((int)$assignment['id'],$clientId,$field,$type==='address_refs'?'address':'business_person',$records);return array_column($records,'public_id');}
    private function addressValues(array $p):array{$types=['principal','business','mailing','registered_office','operating_location','billing','other'];$type=(string)($p['address_type']??'');if(!in_array($type,$types,true))throw new AlchemizeRequestException(422,'VALIDATION_ERROR','Select a valid address type.');foreach(['line1','city','state','postal_code','country'] as $f)if(trim((string)($p[$f]??''))==='')throw new AlchemizeRequestException(422,'VALIDATION_ERROR','Complete all required address fields.');return ['address_type'=>$type,'label'=>$this->text($p['label']??null,100),'line1'=>$this->text($p['line1'],180),'line2'=>$this->text($p['line2']??null,180),'city'=>$this->text($p['city'],120),'state'=>$this->text($p['state'],120),'postal_code'=>$this->text($p['postal_code'],50),'country'=>$this->text($p['country'],120),'is_primary'=>!empty($p['is_primary'])?1:0];}
    private function personValues(array $p):array{$roles=['owner','member','manager','officer','authorized_representative','authorized_contact','decision_maker','administrative_contact','other'];$role=(string)($p['role_type']??'');if(!in_array($role,$roles,true)||trim((string)($p['name']??''))==='')throw new AlchemizeRequestException(422,'VALIDATION_ERROR','A name and valid relationship are required.');$ownership=null;if(in_array($role,['owner','member'],true)&&($p['ownership_percentage']??'')!==''){$ownership=(float)$p['ownership_percentage'];if($ownership<0||$ownership>100)throw new AlchemizeRequestException(422,'VALIDATION_ERROR','Ownership percentage must be between 0 and 100.');}return ['name'=>$this->text($p['name'],180),'role_type'=>$role,'title'=>$this->text($p['title']??null,120),'email'=>$this->text($p['email']??null,254),'phone'=>$this->text($p['phone']??null,40),'ownership_percentage'=>$ownership,'is_authorized_contact'=>!empty($p['is_authorized_contact'])?1:0,'is_decision_maker'=>!empty($p['is_decision_maker'])?1:0,'is_primary'=>!empty($p['is_primary'])?1:0,'client_notes'=>$this->text($p['client_notes']??null,500)];}
    private function text(mixed $v,int $max):?string{$s=trim((string)$v);if($s==='')return null;if(alchemize_text_length($s)>$max)throw new AlchemizeRequestException(422,'VALIDATION_ERROR','A profile value is too long.');return $s;}
    private function profileHasValue(array $profile,string $key):bool{$aliases=['alternate_business'=>'legal_business_name','registrar'=>'domain_registrar','professional_email_exists'=>'business_email'];$target=$aliases[$key]??$key;foreach(['client','business'] as $group){$value=$profile[$group][$target]??null;if($value!==null&&$value!==''&&$value!==[])return true;}if($key==='business_people')return ($profile['people']??[])!==[];if($key==='addresses')return ($profile['addresses']??[])!==[];return false;}
    private function notFound():never{throw new AlchemizeRequestException(404,'NOT_FOUND','The requested intake was not found.');}
}
